// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monaco.Template.Backend.Application.Persistence;

#nullable disable

namespace Monaco.Template.Backend.Application.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[OutboxId] IS NOT NULL");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[InboxMessageId] IS NOT NULL AND [InboxConsumerId] IS NOT NULL");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("Monaco.Template.Backend.Domain.Model.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("WebSiteUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Monaco.Template.Backend.Domain.Model.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c064eff-a037-a6a3-06ec-92f662903af3"),
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("a8b54a61-35d8-9b82-76e4-c709561d9952"),
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("9f420922-9842-0d2d-616d-dacee7c25db7"),
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("26253117-7664-92a9-1a3c-b15cf4bf4c78"),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("ba510e09-5109-42a2-63f0-32d7ede12a5a"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("359da8da-68eb-9466-855d-f0f381f715b8"),
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = new Guid("01ec70b8-6aad-3770-a129-62c0fc294791"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("7d62846b-1841-882f-1cc4-85e2edeea265"),
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("269928e1-37c5-32e0-60c5-bc6da2b8240e"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("7fce71e6-a14d-5d96-2dc1-1fc6779e02d3"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("4cf81cef-66a5-a117-3297-884134e903ee"),
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("08b5d3d0-89ed-a66f-3175-05316ae4a309"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("d7bd1f34-6ef7-43a6-24ed-53bca003086c"),
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("0d69d315-2825-2d05-9c04-ba1ad47180ac"),
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("52f81e1e-6903-88e8-199f-cfc5139b0c69"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("52b13dd7-28fc-9bba-8d59-5c2209531bf5"),
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("8b9ac6d0-2320-3f99-8db7-d78c5d53151a"),
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("c12db9c7-7ca1-4aec-34f1-7d0bb4713ca8"),
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("e34dc09e-2df2-3661-90e1-f03154d45caf"),
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("cf59ee2f-144d-99ac-9048-eafaba1f4732"),
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("1a426c53-787f-527c-5471-c505d6403603"),
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("fae877c5-4806-05e8-2068-950cdcea6ba9"),
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("e0276db5-123f-6028-9e3e-eb43f2e06c47"),
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("72499e6c-80a1-32c3-2692-7216abe7815b"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("ba408210-2ea9-8c6c-1d5d-7e33973f1c99"),
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = new Guid("99532f86-827d-39ba-1c01-b9795ec60bf4"),
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("f16e701a-5dbf-a441-3305-20ac536d34dc"),
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("ff0258f4-35a2-220b-9d9d-f0fe28226cc3"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("f8135306-1323-4f48-7a4b-8d0427cb075b"),
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = new Guid("4676b79b-461c-95de-9871-041d2e0b130b"),
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("42f62587-3470-5967-77e3-f9b0cf285d90"),
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("01deb5a8-6bd7-1879-9d4b-cb73dd0e9a97"),
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("ff7c5aa2-6b56-218e-491a-42f4c67ca4a9"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("77b88575-0e8c-82d0-72bf-06f638b7485f"),
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("758d4f58-7371-36c1-26c2-fcdb993806eb"),
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("97c787c7-915b-4878-3aa2-6ca1eec02f65"),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("003548f7-318a-6f99-8a27-d62963b64cb5"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("63a948ca-178b-93da-4fdd-e6be10b49a42"),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("6d2bc2ca-2f37-3698-7f08-b7b3eeda5bf5"),
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("d9e7fd6d-77f2-8e76-0174-4c17df936d4e"),
                            Name = "Congo (Congo-Brazzaville)"
                        },
                        new
                        {
                            Id = new Guid("16eded64-8619-2b73-682f-a703c1cb2d76"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("7915a976-5224-94f8-232f-ac163a11630c"),
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("b6ed03e6-096c-3f87-093d-f3ff4bf34c24"),
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("d7506bd0-454d-1b83-39e0-905836535271"),
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("caf14a3d-777d-0ee5-63a9-1c3da4e81458"),
                            Name = "Czechia (Czech Republic)"
                        },
                        new
                        {
                            Id = new Guid("da82e26d-40bd-0866-0822-3d5468a36c3e"),
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = new Guid("57dc70e9-17ec-995b-5a60-a7c029b1476a"),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("8c6486fe-2680-4725-1ef3-3d56e3100f08"),
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("d7e310ab-99c3-0a50-2ead-57a2823433ee"),
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("555a4e83-0151-7a10-2072-6cc9f4ac77c1"),
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("2908f020-3d75-3f9a-1a7f-020d1f8d5553"),
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("89bd993a-4eaa-6bae-8cf9-22f766fa2a1e"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("ab1e3408-7157-2629-29a5-fbd6a61d92a9"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("e58f3cfd-069a-4457-23ef-9df8d7fe9ba0"),
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("5e7808be-01a7-9495-2320-314ce20871f3"),
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("5198e2c0-8107-5bcf-90b4-0054eac52295"),
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("cfa8f583-23d4-1475-57ea-ef72ae7b633f"),
                            Name = "Eswatini (fmr. \"Swaziland\")"
                        },
                        new
                        {
                            Id = new Guid("637e0fb3-34ed-6a1b-7524-3d6cd3155d35"),
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("6459ce24-8398-57e0-4a31-48addb374e6d"),
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("d726f074-4b1d-3043-39eb-f9b4ab9b2344"),
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("a5d734a1-021d-9b50-6fd4-b8f24bb96b12"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("a64406fb-51f7-2ed2-31af-847f9cf16783"),
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("967f775b-3c8b-889d-5189-ee71f59f520e"),
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("914f8571-1cac-3f1b-14ef-71aa91836616"),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("d4249520-8674-a2c1-0084-683d7aea64db"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("4fa88e4e-344a-32f8-a5ef-4ef2c33858d2"),
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("a9fe165c-96e6-6bdf-99b0-68f7b2972ef6"),
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("6dfb0c67-2ab9-a5bc-1c58-5eaf76016b9d"),
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("c8f8a591-79c3-a19e-94dd-1c96ed1aa23a"),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("b0ac51a0-0128-4070-a49f-19b3dc5e8135"),
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("d9060b41-6ea0-8efa-1dfe-ce293774947b"),
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("c79ec6ec-2f3d-0c12-8658-5ccbc1a20a77"),
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("60a26e14-90ee-5838-4d27-3672a8e88c48"),
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("a2c0a247-350e-85e6-9009-8106f5fd49b2"),
                            Name = "Holy See"
                        },
                        new
                        {
                            Id = new Guid("d2300477-7258-17b8-7e8a-cf65f06a325f"),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("81f4a56e-5d53-47f3-52c3-2cd843434126"),
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("9c239e38-640c-3fb2-0bc8-8edaace24c70"),
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("a0d1f65e-307d-59fa-7792-24a5f0359889"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("5b9d725f-4e89-0181-74ae-ba87e96590d7"),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("afa8b53f-45e6-391f-1c60-db81be664b1b"),
                            Name = "Iran"
                        },
                        new
                        {
                            Id = new Guid("59bee04d-32a1-1e53-4a1b-599671a4a693"),
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("18bd53bd-3519-69ef-1148-3453ad744c0f"),
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("6704c135-5af7-88e9-16a5-ad4656fa1be2"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("cf1fcfbe-11fa-7009-0d71-d2cf5c80a334"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("038fb0db-7012-50fb-9ace-3b9f240d9627"),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("12d9457c-1c12-9961-60cf-ec2ee534843a"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("aa9d471d-3f2f-5d42-3d01-443a83c12f59"),
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("7708a52a-1d62-8f8b-0a4d-6028ed834994"),
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("f27f4ccb-4e04-8e05-456e-621788247647"),
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("c7fc5498-271d-1027-343a-1560793d1c26"),
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("ee007dac-7417-54e4-18c2-ec6a678ba130"),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("20bfffe5-7601-63e6-3574-9346e80d5d5c"),
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("6a5e5c1a-4d04-237e-8415-a7f93945133b"),
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("1e2e1979-539d-128f-538e-c30b8ba49b42"),
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("29e7cce5-28a0-990c-6ded-54e96cad9caa"),
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("dbe19dde-374b-68a8-41e0-48d5195aa6f5"),
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("2092625a-45e4-166e-53cf-bb48408f1b09"),
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("9d8cf3fc-222d-a56c-211b-8e8e9edf54e0"),
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("b232a961-1224-244f-27a1-06cba2046c22"),
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("a681eaeb-1fa0-12d7-93fb-e33a13c188e9"),
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("5ee9fcd4-5680-3cb4-1174-d85201e82367"),
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("408f1ee6-42d3-a211-67c5-32f601b79bd9"),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("341651be-9d9c-206b-9162-aad732979787"),
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("40563307-5fe1-97d4-9d10-d81af5138548"),
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("43da6311-4ed9-9a74-9a46-82847f79a7c3"),
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("c3700331-07c2-264c-2335-ba61bc718cac"),
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("1e3241f2-78b6-56e8-4c2d-4a50647973cf"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("bdf3f266-9570-2bb9-330f-9ea51c927068"),
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = new Guid("572563f8-2f44-603d-857e-3f8230035e82"),
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("e8b389a9-0afd-4904-46af-464012f102c2"),
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("2f7432c5-405f-3f99-4bc3-35e318bd66cc"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("94e831a3-3e52-7bb4-7616-dc0ac75c2d1d"),
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = new Guid("abe01fc7-a484-7a8e-74b6-c5fa27554505"),
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = new Guid("6a265dd9-314e-2eb2-a4f8-3faf9c11a39d"),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("a484eabd-775b-4b7d-595b-3f5d857f5052"),
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("46fd6123-5206-2c2c-2832-953d13847069"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("09ee26e3-5c82-221e-0729-e47d663a949c"),
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("aa6f7328-8f52-9bd1-0bba-9fb4f18a926e"),
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("4ebfeb1d-67d6-2499-5346-740f737100ee"),
                            Name = "Myanmar (formerly Burma)"
                        },
                        new
                        {
                            Id = new Guid("aa29ea0b-2681-3475-6e16-1b7d164b081a"),
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("d9a21a29-a0e2-71bc-7308-548cc27b19f1"),
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("2c4ab1fa-60da-7c87-35b3-ac6903455853"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("cb245d05-3293-7315-7ee1-eef8a383319c"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("472e0e57-77f5-9c34-8e10-a621c97108f7"),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("350dc86e-03b2-2c20-1908-b4de7d179de7"),
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("9b36a6c2-4739-69a2-068b-c0b3c87c6f67"),
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("2ca00749-35c0-511b-9c2c-b53e5a8f0a71"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("10ef2f04-4d96-5b5e-316f-b373a88731be"),
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = new Guid("51c38ab5-0b2b-2994-4eb2-c8e82fe17950"),
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("c1c8ec1f-58ce-3931-7ad7-ad4b55c14a85"),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("859adf7d-1bf9-87d1-6a9b-4a06ebab6796"),
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("6133196d-26d0-5f8e-5792-6215aefd668d"),
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("3881b3b6-a332-3d35-8a73-43acfbf9045b"),
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("9a79f7fb-27a4-811b-88c3-9de906521017"),
                            Name = "Palestine State"
                        },
                        new
                        {
                            Id = new Guid("f5b0c42e-3b0e-3808-1922-fdae58ea075c"),
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("16ff3157-a061-2e81-5ca6-b71e3619376e"),
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("1b84f08e-8e6d-5779-967c-a162c2307153"),
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("f625e01e-4a07-7ff3-0a7e-ce6e27b586ff"),
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("19be2963-072b-2f4b-0f85-558d90ee1770"),
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("fc432d5c-66dd-5660-8186-da84b4e164a0"),
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("2b1486b9-0cfa-2dc6-3f70-4ee2f11955b4"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("47ac0edf-9beb-345b-0e4b-bccb0c1a2032"),
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("d5cb2660-9af9-0385-8a99-52871814043d"),
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("6fa56ae5-2091-39c4-0010-ae74ffa2a0f2"),
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("362ac8d8-6fba-a641-8272-958f9e553b54"),
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("c3553d72-9d17-04d8-6692-12a5a7250008"),
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = new Guid("fd3ab0e3-279a-107a-88e0-93ee1bb45ffb"),
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = new Guid("420b0acb-a1b0-27e5-45fc-3c6e96f25361"),
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = new Guid("37425b6c-2940-370c-805d-27cb7af97f88"),
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("b6667319-a515-1cf5-7392-92e15c52438d"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("75c8834a-67e9-9ee5-65bb-e2db6a937074"),
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = new Guid("1e9ab108-4d4b-1812-21d9-5c90d7d897ea"),
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("3cb2d6c7-8bb5-191d-183d-b201063d5491"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("1995e756-0e82-9463-1627-feeb766d2d0d"),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("1ff73b0c-27c4-9d4a-3d5b-ec77a6612d56"),
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("6df0d56f-3b4e-33fe-6d5f-74da585ea5d0"),
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("912f9045-7a3b-151b-2c06-19f899d1787a"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("53e7d0fc-816f-59dd-7b4a-0ade62330830"),
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("a522756f-2fd9-48d1-7443-dd1546fd8b37"),
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("5f47ed3b-0b54-95aa-93e8-16bf035c9247"),
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("b58da294-9556-8ece-163f-3d89514017a7"),
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("03a82f52-22d5-8259-1072-429791258b72"),
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("55cafe8e-1585-278e-5736-bab16f1b1b8d"),
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("9d2d676f-97fb-952c-06a9-09d4e9696631"),
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("534a826b-70ef-2128-1a4c-52e23b7d5447"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("932a43ac-56dc-951e-7de5-996314e92e9c"),
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("6c4a7b61-3bfd-4a47-95a3-0ca86c72521f"),
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("9a0a2c1d-3475-3554-9d18-b11946af6086"),
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("896ef05e-0fe4-92a6-229e-63d7a26e0625"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("bb0b41a9-7363-5922-9ce0-939412a9036e"),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("7b9c857e-3fbd-3d19-38cf-f204da39890c"),
                            Name = "Syria"
                        },
                        new
                        {
                            Id = new Guid("d7cd92d3-4522-5a78-3533-816fc61a293f"),
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("fa81562d-1bc4-944c-86a9-6cc5af502265"),
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("439e3108-0908-4d90-6f5c-1974362b74b1"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("47e7cc9c-4368-8ab3-056b-66a1351c24cd"),
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = new Guid("492a6eb7-5ca3-8e50-3559-c71205b71c3b"),
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("e376c876-6960-270c-8744-583fb7a72f55"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("2f7c276f-4d0d-9368-4132-c04149924bb5"),
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = new Guid("93ba288b-2a62-1880-1e20-aeb705431890"),
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("c576d8f0-5300-2436-2d17-48b699214549"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("a9c5d1ec-319a-085c-1ee3-80ae15bd27ed"),
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("95938676-73d1-2031-219d-dc67ba314bdf"),
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("2cfae83c-0f45-72d1-4624-5af1e10e6147"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("1b837dfa-0bda-54f3-918a-beef19f691e5"),
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("f7675604-4744-6d6f-a077-67a3e0c85324"),
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("8f9ec4fb-916f-90ea-5162-f486a0fc0893"),
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("ca111c84-983b-4525-054c-d14dee3a422c"),
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = new Guid("ee06c3ba-4e8c-95c3-88da-6be3f23b9aaa"),
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("2f02c930-1d71-8ca6-49e7-0d3679a522ea"),
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("28dc2817-94b4-955d-10bc-6a8793dd386c"),
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("9c9e3bca-5880-437f-4f18-d6998d90173f"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("5a3893d1-1e36-310c-7633-8f36ffa26315"),
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("a2689ae3-3643-6250-a748-8f055cc72da8"),
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("be447a08-0a85-5779-8c65-cf15c2c9a5a8"),
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("c776f397-182b-6d0d-09f2-4e440dc093d3"),
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Monaco.Template.Backend.Domain.Model.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsTemp")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("File", (string)null);

                    b.HasDiscriminator().IsComplete(true).HasValue("File");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Monaco.Template.Backend.Domain.Model.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefaultPictureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DefaultPictureId")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ProductPicture", b =>
                {
                    b.Property<Guid>("PicturesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PicturesId", "ProductId");

                    b.HasIndex("PicturesId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPicture");
                });

            modelBuilder.Entity("Monaco.Template.Backend.Domain.Model.Entities.Document", b =>
                {
                    b.HasBaseType("Monaco.Template.Backend.Domain.Model.Entities.File");

                    b.HasDiscriminator().HasValue("Document");
                });

            modelBuilder.Entity("Monaco.Template.Backend.Domain.Model.Entities.Image", b =>
                {
                    b.HasBaseType("Monaco.Template.Backend.Domain.Model.Entities.File");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ThumbnailId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ThumbnailId")
                        .IsUnique()
                        .HasFilter("[ThumbnailId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Image");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Monaco.Template.Backend.Domain.Model.Entities.Company", b =>
                {
                    b.OwnsOne("Monaco.Template.Backend.Domain.Model.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("County")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PostCode")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Street")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("CompanyId");

                            b1.HasIndex("CountryId");

                            b1.ToTable("Company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");

                            b1.HasOne("Monaco.Template.Backend.Domain.Model.Entities.Country", "Country")
                                .WithMany()
                                .HasForeignKey("CountryId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Country");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Monaco.Template.Backend.Domain.Model.Entities.Product", b =>
                {
                    b.HasOne("Monaco.Template.Backend.Domain.Model.Entities.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monaco.Template.Backend.Domain.Model.Entities.Image", "DefaultPicture")
                        .WithOne()
                        .HasForeignKey("Monaco.Template.Backend.Domain.Model.Entities.Product", "DefaultPictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("DefaultPicture");
                });

            modelBuilder.Entity("ProductPicture", b =>
                {
                    b.HasOne("Monaco.Template.Backend.Domain.Model.Entities.Image", null)
                        .WithMany()
                        .HasForeignKey("PicturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monaco.Template.Backend.Domain.Model.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Monaco.Template.Backend.Domain.Model.Entities.Image", b =>
                {
                    b.HasOne("Monaco.Template.Backend.Domain.Model.Entities.Image", "Thumbnail")
                        .WithOne()
                        .HasForeignKey("Monaco.Template.Backend.Domain.Model.Entities.Image", "ThumbnailId");

                    b.OwnsOne("Monaco.Template.Backend.Domain.Model.ValueObjects.GpsPosition", "Position", b1 =>
                        {
                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("Latitude")
                                .HasColumnType("real");

                            b1.Property<float>("Longitude")
                                .HasColumnType("real");

                            b1.HasKey("ImageId");

                            b1.ToTable("File");

                            b1.WithOwner()
                                .HasForeignKey("ImageId");
                        });

                    b.OwnsOne("Monaco.Template.Backend.Domain.Model.ValueObjects.ImageDimensions", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Height")
                                .HasColumnType("int");

                            b1.Property<int>("Width")
                                .HasColumnType("int");

                            b1.HasKey("ImageId");

                            b1.ToTable("File");

                            b1.WithOwner()
                                .HasForeignKey("ImageId");
                        });

                    b.Navigation("Dimensions")
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("Monaco.Template.Backend.Domain.Model.Entities.Company", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
