<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
  </ItemGroup>

  <!--#if (templateDebug)-->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);auth;commonLibraries;filesSupport;massTransitIntegration</DefineConstants>
  </PropertyGroup>

  <!--#endif-->
  <ItemGroup>
    <!--#if (commonLibraries)-->
    <ProjectReference Include="..\Monaco.Template.Backend.Common.Application\Monaco.Template.Backend.Common.Application.csproj" />
    <!--#else-->
    <PackageReference Include="Monaco.Template.Backend.Common.Application" />
    <!--#endif-->
    <!--#if (massTransitIntegration)-->
    <ProjectReference Include="..\Monaco.Template.Backend.Messages\Monaco.Template.Backend.Messages.csproj" />
    <!--#endif-->
    <!--#if (filesSupport)-->
    <!--#if (commonLibraries)-->
    <ProjectReference Include="..\Monaco.Template.Backend.Common.BlobStorage\Monaco.Template.Backend.Common.BlobStorage.csproj" />
    <!--#else-->
    <PackageReference Include="Monaco.Template.Backend.Common.BlobStorage" />
    <!--#endif-->
    <!--#endif-->
    <!--#if (commonLibraries)-->
    <ProjectReference Include="..\Monaco.Template.Backend.Common.Infrastructure\Monaco.Template.Backend.Common.Infrastructure.csproj" />
    <!--#else-->
    <PackageReference Include="Monaco.Template.Backend.Common.Infrastructure" />
    <!--#endif-->
    <ProjectReference Include="..\Monaco.Template.Backend.Domain\Monaco.Template.Backend.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!--#if (filesSupport)-->
    <PackageReference Include="AsyncEnumerator" />
    <PackageReference Include="ExifLibNet" />
    <!--#endif-->
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <!--#if (massTransitIntegration)-->
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <!--#endif-->
    <!--#if (filesSupport)-->
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <!--#endif-->
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Migrations\" />
  </ItemGroup>
</Project>