<Project Sdk="Microsoft.NET.Sdk">

  <!--#if (templateDebug)-->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);auth;commonLibraries;filesSupport</DefineConstants>
  </PropertyGroup>

  <!--#endif-->
  <ItemGroup>
    <!--#if (commonLibraries)-->
    <ProjectReference Include="..\Monaco.Template.Backend.Common.Domain\Monaco.Template.Backend.Common.Domain.csproj" />
    <!--#else-->
    <PackageReference Include="Monaco.Template.Backend.Common.Domain" />
    <!--#endif-->
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Throw" />
  </ItemGroup>

</Project>